name: Docker
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/mikesupertrampster/simple-json-server:${{ env.GITHUB_REF }}
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/mikesupertrampster/simple-json-server:${{ env.GITHUB_REF }}
          format: template
          template: '@/contrib/sarif.tpl'
          output: trivy-results.sarif
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: trivy-results.sarif